version: '3.4'

services:
  
  bot:
    build: .
    restart: always
    networks:
      - mongo_default
    volumes:
      - /mnt/nas-data/waambot-archives:/archives:rw

networks:
  mongo_default: 
    external: true
